version: '3.8'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    volumes:
      - kong_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - kong_net

  kong-migration:
    image: kong:3.4
    container_name: kong-migration
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PG_DATABASE: kong
    command: kong migrations bootstrap
    networks:
      - kong_net

  kong:
    image: kong:3.4
    container_name: kong
    restart: unless-stopped
    depends_on:
      - kong-migration
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_GUI_URL: https://koung.ragam.io
      KONG_ADMIN_GUI_HOST: koung.ragam.io
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_ENFORCE_RBAC: "on"
      KONG_ADMIN_GUI_AUTH: basic-auth
      KONG_ADMIN_GUI_SESSION_CONF: '{"secret":"kong-admin-secret-key","storage":"kong","cookie_secure":false,"cookie_name":"kong_admin_session","cookie_lifetime":86400}'
      KONG_ADMIN_GUI_SSL: "off"
      KONG_ADMIN_GUI_AUTH_CONF: '{"anonymous":"","credential_names":["basic-auth"],"header_names":["Authorization"],"hide_credentials":false}'
      KONG_PASSWORD: "Beranekaragam2024"
      KONG_ADMIN_GUI_AUTH_TYPE: basic-auth
      KONG_ADMIN_GUI_AUTH_PLUGIN: basic-auth
      KONG_ADMIN_GUI_AUTH_CONF_KEY: kong_admin
      KONG_ADMIN_GUI_FLAGS: "read_only=off"
      KONG_ADMIN_GUI_API_URL: https://koung-listen.ragam.io
      KONG_ADMIN_API_URI: https://koung-listen.ragam.io
      KONG_CORS_ORIGINS: https://koung.ragam.io,https://koung-listen.ragam.io
      KONG_CORS_METHODS: GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS
      KONG_CORS_HEADERS: Content-Type,Accept,Authorization,Origin,X-Requested-With,Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin
      KONG_CORS_EXPOSED_HEADERS: "*"
      KONG_CORS_MAX_AGE: 3600
      KONG_CORS_CREDENTIALS: false
      KONG_CORS_PREFLIGHT_CONTINUE: false
      # KONG_HEADERS: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Headers,Access-Control-Allow-Credentials,Access-Control-Max-Age
    ports:
      - "80:8000"
      - "8001:8001"
      - "443:8443"
      - "444:8444"
      - "8002:8002"
    networks:
      - kong_net

networks:
  kong_net:
    name: kong_net
    driver: bridge

volumes:
  kong_data:
    driver: local